### PR TITLE
Initial working app for first release

### PR DESCRIPTION
**Pull request by jethror1**
- takes high level and low level configs as inputs to trigger required analysis
- handles everything required (I think) for v1 other than sample sheet validation

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r3, 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1)* status: 3 of 19 files reviewed, 9 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[dxapp.json, line 11 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo2KjW2mcNgE6qz0nB:-Moo2KjW2mcNgE6qz0nC:b-itgpmg) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/dxapp.json#L11)):*
> ```
>       "name": "project",
>       "label": "DNAnexus project id",
> ```
This might benefit from a help to describe how it's going to be used by the app
___
*[dxapp.json, line 17 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo2_xaCvpNicxzeeNp:-Moo2_xaCvpNicxzeeNq:bkbg7mn) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/dxapp.json#L17)):*
> ```
> "name": "sentinel_file"
> ```
Ditto help text
___
*[dxapp.json, line 113 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo3Gwd1R-KryXEzz7p:-Moo3Gwd1R-KryXEzz7q:bgrq0nu) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/dxapp.json#L113)):*
> ```
> "release": "18.04"
> ```
Could this be 20?
___
*[README.md, line 36 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo4Mvz8UG4tPg9-txr:-Moo4Mvz8UG4tPg9-txs:b-cc70mx) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/README.md#L36)):*
> ```
> here
> ```
Here? Missing link?
___
*[README.md, line 42 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo4wJO6iklQZI2du-v:-Moo4wJO6iklQZI2du-w:bf7ct76) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/README.md#L42)):*
> ```
> (boolean): if to run bcl2fastq
> ```
if `True` run bcl2fastq ?
___
*[README.md, line 50 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo5O4g-7N9TatjPRbV:-Moo5O4g-7N9TatjPRbW:b-kbbe0l) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/README.md#L50)):*

<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

>     "name": "Config for myeloid assay",
>     "version": "v1.0.0",
>     "details": "Includes main Uranus workflow, multi-fastqc and uranus annotation workflow",
>     "demultiplex": true,
>     "users": {
>         "org-emee_1": "ADMIN"
</details>

Missing the required `executables` key/value decribed above
___
*[README.md, line 59 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo63hPCll39Gk23Kx0:-Moo63hQCssAq-rQzcHB:b-4plkxs) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/README.md#L59)):*
> ```
> will be used to name output directory if using output variable naming (see below)
> ```
Does this sentence make sense? I will see below...
___
*[README.md, line 88 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo76NZCQ6KwMSQmdPN:-Moo76NZCQ6KwMSQmdPO:btsgile) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/README.md#L88)):*
> ```
> /output/OUT-FOLDER/APP-NAME
> ```
~~Does this need explanation? Is it all supposed to be the same for each app, or does it need to be edited?
(I know the answer, but for clarity)~~
Done
___
*[README.md, line 133 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo7ruj8mDFa_MfZUhU:-Moo7ruj8mDFa_MfZUhV:b9q1m75) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/README.md#L133)):*
> ```Markdown
> 
>     ```
> ```

Missing

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1)* status: 3 of 19 files reviewed, 16 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[example/example_populated_config.json, line 7 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-MoqyA8BDWzD0R3XVyVY:-MoqyA8CDOdS469TmHzr:b-ywio5j) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/example/example_populated_config.json#L7)):*
> ```
> ADMIN
> ```
Maybe make this CONTRIBUTE instead, just so that we don't end up with this being used as a template resulting in lots of ADMIN being assigned to projects
___
*[resources/home/dnanexus/run_workflows.py, line 50 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mor-pz63nxQ5tjQuEfq:-Mor-pz63nxQ5tjQuEfr:b-6ohql6) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/resources/home/dnanexus/run_workflows.py#L50)):*
> ```
> else create one
> ```
Could use a better description in the docstring
this function only finds, it's not a get_or_create type function
___
*[resources/home/dnanexus/run_workflows.py, line 58 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mor05X80SUJhLfzyp0L:-Mor05X80SUJhLfzyp0M:bhx47qr) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/resources/home/dnanexus/run_workflows.py#L58)):*
> ```
> => create new one
> ```
No code creates one in this function, this might be misleading
___
*[resources/home/dnanexus/run_workflows.py, line 65 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mor0Ujx7qojhEenk2-e:-Mor0Ujx7qojhEenk2-f:brgpprf) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/resources/home/dnanexus/run_workflows.py#L65)):*
> ```
> print('WARNING')
> ```
Is warning rather than error the right thing to do here, if this should not happen?
___
*[resources/home/dnanexus/run_workflows.py, line 74 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mor1u1zA5mbZSCeQq_z:-Mor1u1zA5mbZSCeQqa-:bd2cvvj) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/resources/home/dnanexus/run_workflows.py#L74)):*
> ```
> create_
> ```
Should this be `get_or_create_` to more accurately describe what it's doing?
___
*[resources/home/dnanexus/run_workflows.py, line 142 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mor5Edo2WY_zywr4xp_:-Mor5Edo2WY_zywr4xpa:b-ephv7v) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/resources/home/dnanexus/run_workflows.py#L142)):*
> ```
> else:
> ```
Perhaps a comment to explain when else is executed, as it's a little unintuitive and I've seen the for/else pattern confuse people before
___
*[resources/home/dnanexus/run_workflows.py, line 310 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mor8SdJ-pCMG6ZUU62s:-Mor8SdJ-pCMG6ZUU62t:btri6ax) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/resources/home/dnanexus/run_workflows.py#L310)):*
> ```Python
>     return input_dict
> ```

Note to self: Continue review from here

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 7 of 14 files at r1, 6 of 11 files at r3, 3 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1)* status: 16 of 19 files reviewed, 21 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[resources/home/dnanexus/run_workflows.py, line 358 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Morft9G-wbOdfMpAcMS:-Morft9G-wbOdfMpAcMT:bx3y11m) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/resources/home/dnanexus/run_workflows.py#L358)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> def get_dependent_jobs(params, job_outputs_dict, sample=None):
>     """
>     If app / workflow depends on previous job(s) completing these will be
>     passed with depends_on = [analysis_1, analysis_2...]. Get all job ids for
>     given analysis to pass to dx run.
> ```
</details>

https://cuhbioinformatics.atlassian.net/browse/BINFRA-27
___
*[src/eggd_conductor.sh, line 24 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-MormqCz5YyNo4SgLcUP:-MormqCz5YyNo4SgLcUQ:b-etxw0h) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/src/eggd_conductor.sh#L24)):*
> ```
> ·········
> ```
whitespace
___
*[src/eggd_conductor.sh, line 120 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-MorqNNm639D5kH8u1aB:-MorqNNm639D5kH8u1aC:b-3w3yej) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/src/eggd_conductor.sh#L120)):*
> ```
> ·····
> ```
ecapsetihw
___
*[src/eggd_conductor.sh, line 139 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-MorqbJq6FxD0_Daq06D:-MorqbJq6FxD0_Daq06E:b3zhh8x) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/src/eggd_conductor.sh#L139)):*
> ```
> ·····
> ```
ǝɔɐdsǝʇᴉɥʍ
___
*[src/eggd_conductor.sh, line 254 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-MorujskDCBl8Cyuohn0:-MorujskDCBl8Cyuohn1:b-49kx3h) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/src/eggd_conductor.sh#L254)):*
> ```
> ·········
> ```
ʍɥᴉʇǝsdɐɔǝ

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1)* status: 14 of 21 files reviewed, 21 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[dxapp.json, line 11 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo2KjW2mcNgE6qz0nB:-MpI60UoDvoQzFr1sIMR:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/dxapp.json#L11)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>       "name": "project",
>       "label": "DNAnexus project id",
> ```
This might benefit from a help to describe how it's going to be used by the app
</blockquote></details>

Done.
___
*[dxapp.json, line 17 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo2_xaCvpNicxzeeNp:-MpI66TU6g-0XHOZzgVd:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/dxapp.json#L17)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> "name": "sentinel_file"
> ```
Ditto help text
</blockquote></details>

Done.
___
*[dxapp.json, line 113 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo3Gwd1R-KryXEzz7p:-MpI69WJ090do_GzePTQ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/dxapp.json#L113)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> "release": "18.04"
> ```
Could this be 20?
</blockquote></details>

Done.
___
*[README.md, line 36 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo4Mvz8UG4tPg9-txr:-MpI6VH7-xbbghQof73k:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/README.md#L36)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> here
> ```
Here? Missing link?
</blockquote></details>

Done.
___
*[README.md, line 42 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo4wJO6iklQZI2du-v:-MpI6jHEAIfJVAkGjiKh:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/README.md#L42)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> (boolean): if to run bcl2fastq
> ```
if `True` run bcl2fastq ?
</blockquote></details>

Done.
___
*[README.md, line 50 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo5O4g-7N9TatjPRbV:-MpI6ym_-pKivXKHNCnl:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/README.md#L50)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>


>     "name": "Config for myeloid assay",
>     "version": "v1.0.0",
>     "details": "Includes main Uranus workflow, multi-fastqc and uranus annotation workflow",
>     "demultiplex": true,
>     "users": {
>         "org-emee_1": "ADMIN"

Missing the required `executables` key/value decribed above
</blockquote></details>

Done.
___
*[README.md, line 59 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo63hPCll39Gk23Kx0:-MpI7uZv4oFT7Hy3gnl2:b-jdqce8) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/README.md#L59)):*
> will be used to name output directory if using outpu
so...did it make sense?
___
*[README.md, line 88 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Moo76NZCQ6KwMSQmdPN:-MpI8J7Y4a2T9-NEJ8NR:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/README.md#L88)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> /output/OUT-FOLDER/APP-NAME
> ```
~~Does this need explanation? Is it all supposed to be the same for each app, or does it need to be edited?
(I know the answer, but for clarity)~~
Done
</blockquote></details>

Done.
___
*[example/example_populated_config.json, line 7 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-MoqyA8BDWzD0R3XVyVY:-MpI8nHkCK9Oeui8vcTJ:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/example/example_populated_config.json#L7)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ADMIN
> ```
Maybe make this CONTRIBUTE instead, just so that we don't end up with this being used as a template resulting in lots of ADMIN being assigned to projects
</blockquote></details>

Done.
___
*[resources/home/dnanexus/run_workflows.py, line 50 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mor-pz63nxQ5tjQuEfq:-MpIA5N48RbZnD31XbN8:bc8boik) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/resources/home/dnanexus/run_workflows.py#L50)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> else create one
> ```
Could use a better description in the docstring
this function only finds, it's not a get_or_create type function
</blockquote></details>

changed it
___
*[resources/home/dnanexus/run_workflows.py, line 58 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mor05X80SUJhLfzyp0L:-MpIADY_Bt6Fe4RR1eGu:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/resources/home/dnanexus/run_workflows.py#L58)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> => create new one
> ```
No code creates one in this function, this might be misleading
</blockquote></details>

Done.
___
*[resources/home/dnanexus/run_workflows.py, line 65 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mor0Ujx7qojhEenk2-e:-MpIAKrAA00h6-YnEWMk:bdldnkm) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/resources/home/dnanexus/run_workflows.py#L65)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> print('WARNING')
> ```
Is warning rather than error the right thing to do here, if this should not happen?
</blockquote></details>

as in raise an exception and stop?
___
*[resources/home/dnanexus/run_workflows.py, line 74 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mor1u1zA5mbZSCeQq_z:-MpIAaM30jbeUT5zmlze:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/resources/home/dnanexus/run_workflows.py#L74)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> create_
> ```
Should this be `get_or_create_` to more accurately describe what it's doing?
</blockquote></details>

Done.
___
*[resources/home/dnanexus/run_workflows.py, line 142 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mor5Edo2WY_zywr4xp_:-MpIAu688D1bl4upvJGl:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/resources/home/dnanexus/run_workflows.py#L142)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> else:
> ```
Perhaps a comment to explain when else is executed, as it's a little unintuitive and I've seen the for/else pattern confuse people before
</blockquote></details>

Done.
___
*[src/eggd_conductor.sh, line 24 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-MormqCz5YyNo4SgLcUP:-MpIB7VA0fY6kf8Cw193:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/src/eggd_conductor.sh#L24)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ·········
> ```
whitespace
</blockquote></details>

Done.
___
*[src/eggd_conductor.sh, line 120 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-MorqNNm639D5kH8u1aB:-MpIBN2Y7lQq25L0N0hm:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/src/eggd_conductor.sh#L120)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ·····
> ```
ecapsetihw
</blockquote></details>

Done.
___
*[src/eggd_conductor.sh, line 139 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-MorqbJq6FxD0_Daq06D:-MpIBNSvBlMISs7OZQfc:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/src/eggd_conductor.sh#L139)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ·····
> ```
ǝɔɐdsǝʇᴉɥʍ
</blockquote></details>

Done.
___
*[src/eggd_conductor.sh, line 254 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-MorujskDCBl8Cyuohn0:-MpIBOlEDwpD3ZvIwGe6:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/src/eggd_conductor.sh#L254)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ·········
> ```
ʍɥᴉʇǝsdɐɔǝ
</blockquote></details>

Done.

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 17 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1)* status: 12 of 28 files reviewed, 23 unresolved discussions (waiting on @JasonLing95, @jethror1, and @mattgarner)

___
*[resources/home/dnanexus/run_workflows.py, line 72 at r12](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mv3A5EF2fH0WzG83YGH:-Mv3A5EF2fH0WzG83YGI:b-rl2a9n) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/d2d6106ac3fa012d493fbdc7d9a4246bcfa8094e/resources/home/dnanexus/run_workflows.py#L72)):*
> ```Python
>         dx ID of given project if found, else returns `None`
>     """
>     dx_projects = list(dxpy.bindings.search.find_projects(
> ```

could use limit=1 since we aren't doing much either when len(projs) > 1 but just taking the proj[0] unless we're logging those proj with more returns.
___
*[test_configs/test_dias_low_level_config.json, line 21 at r12](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mv3ISyy0C7aatbrF358:-Mv3ISyy0C7aatbrF359:bf1vw4p) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/d2d6106ac3fa012d493fbdc7d9a4246bcfa8094e/test_configs/test_dias_low_level_config.json#L21)):*
> ```JSON
>                 "stage-Fy6fpk040vZZPPbq96Jb2KfK.sample": "INPUT-SAMPLE-NAME",
>                 "stage-Fy6fpk040vZZPPbq96Jb2KfK.reads2_fastqgzs": "INPUT-R2",
>                 "stage-Fy6fpk040vZZPPbq96Jb2KfK.reads_fastqgzs": "INPUT-R1",
> ```

there is no closing curly braces for this dict



_Code quote:_
```JSON
            "inputs": {
                "stage-Fy6fpk040vZZPPbq96Jb2KfK.sample": "INPUT-SAMPLE-NAME",
                "stage-Fy6fpk040vZZPPbq96Jb2KfK.reads2_fastqgzs": "INPUT-R2",
                "stage-Fy6fpk040vZZPPbq96Jb2KfK.reads_fastqgzs": "INPUT-R1",
                "stage-Fy6fpV840vZZ0v6J8qBQYqZF.fastqs": "INPUT-R1-R2",
```

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1)* status: 12 of 28 files reviewed, 23 unresolved discussions (waiting on @JasonLing95, @jethror1, and @mattgarner)

___
*[resources/home/dnanexus/run_workflows.py, line 72 at r12](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mv3A5EF2fH0WzG83YGH:-MvJ7v7oCSlIjBK63za2:b-2ilb2b) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/d2d6106ac3fa012d493fbdc7d9a4246bcfa8094e/resources/home/dnanexus/run_workflows.py#L72)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

could use limit=1 since we aren't doing much either when len(projs) > 1 but just taking the proj[0] unless we're logging those proj with more returns.
</blockquote></details>

good point, changed it
___
*[test_configs/test_dias_low_level_config.json, line 21 at r12](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mv3ISyy0C7aatbrF358:-MvJ8CjlCSeGhev4u4_z:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/d2d6106ac3fa012d493fbdc7d9a4246bcfa8094e/test_configs/test_dias_low_level_config.json#L21)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

there is no closing curly braces for this dict
</blockquote></details>

Done.

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1)* status: 11 of 28 files reviewed, 24 unresolved discussions (waiting on @JasonLing95, @jethror1, and @mattgarner)

___
*[resources/home/dnanexus/run_workflows.py, line 982 at r14](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-MvNyom1EBgZzc2DSWkM:-MvNyom1EBgZzc2DSWkN:b-yzdyf) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/30af0d37712d4e98ce9c90b7af8d08fc5ebc94fe/resources/home/dnanexus/run_workflows.py#L982)):*
> ```Python
> 
>     # set context to project for running jobs
>     dxpy.set_workspace_id()
> ```

this is missing a parameter: dxid
I guess it's args.dx_project_id?



_Code quote:_
```Python
dxpy.set_workspace_id()
```

**Review by JasonLing95 — COMMENTED** [review]
> Reviewed 1 of 14 files at r1, 3 of 11 files at r3, 1 of 5 files at r7, 4 of 11 files at r9, 10 of 17 files at r12, 1 of 1 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1)* status: all files reviewed, 22 unresolved discussions (waiting on @jethror1 and @mattgarner)

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1)* status: all files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @mattgarner)

___
*[`resources/home/dnanexus/run_workflows.py` line 65 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mor0Ujx7qojhEenk2-e:-N1nJOnB0cH1xk_iJzAO:b-pik8f4) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/resources/home/dnanexus/run_workflows.py#L65)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

That's what I was thinking. Better to fail than potentially return the wrong thing. 
</blockquote></details>

I'm confused what line this was from as its no longer in the code.... can this be closed or point me to where it was?

**Review by mattgarner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1)* status: all files reviewed, 1 unresolved discussion (waiting on @JasonLing95)

___
*[`resources/home/dnanexus/run_workflows.py` line 65 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-Mor0Ujx7qojhEenk2-e:-N1sMkhsDwKB7xT46jZ0:b9top28) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/a7ccc1758203963702eb8d5ba4b11c85b46b91ad/resources/home/dnanexus/run_workflows.py#L65)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I'm confused what line this was from as its no longer in the code.... can this be closed or point me to where it was?
</blockquote></details>

It's no longer in the code. That's odd, but not the first time I've seen this with reviewable recently. Or maybe this is user error. Either way, this can be resolved

**Review by JasonLing95 — COMMENTED** [review]
> Reviewed 1 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1)* status: 27 of 28 files reviewed, all discussions resolved (waiting on @JasonLing95)

**Review by jethror1 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1#-:-N2NOjUw-gf49HuB3Rtx:bnfp4nl)* status: 27 of 28 files reviewed, all discussions resolved (waiting on @JasonLing95)

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
