### PR TITLE
Some extra functions, some bug fixes, many many many unit tests

### PR DESCRIPTION
**Pull request by jethror1**
## Changes
- added new available key for config files (`inputs_filter`) that allows providing an input field and list of regex patterns to filter down by
  - required in cases where a downstream app takes the output of previous jobs, but only requires a subset of these files (i.e. if all single sample workflows output bam files, but only those for certain sample(s) are needed (such as NA12878 for hap.py))
  - example included in readme
- added `manageDict.check_input_classes` function to check inputs are correct types (i.e. `file` vs `array:file`) to prevent dx errors on running
- fix being able to get upstream `per_run` dependent job IDs where the current app/workflow is running `per_sample` (`ManageDict.get_dependent_jobs` changes)
- fix typo in `ManageDict.link_inputs_to_outputs`
- added many unit tests to cover most of `ManageDict` methods:
```
$ python3 -m pytest -vv resources/home/dnanexus/run_workflows/tests/
=========================================================================================== test session starts ===========================================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/jethro/Projects/eggd_conductor
plugins: Faker-14.0.0
collected 41 items                                                                                                                                                                                        

resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestSearchDict::test_search_key_return_key_level1 PASSED                                                                           [  2%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestSearchDict::test_search_key_return_value_level1 PASSED                                                                         [  4%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestSearchDict::test_search_key_return_array_values PASSED                                                                         [  7%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestSearchDict::test_search_dict_array PASSED                                                                                      [  9%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestReplaceDict::test_replace_level1_keys PASSED                                                                                   [ 12%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestReplaceDict::test_replace_all_value1 PASSED                                                                                    [ 14%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestReplaceDict::test_replace_value_from_key PASSED                                                                                [ 17%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestAddFastqs::test_adding_all_r1 PASSED                                                                                           [ 19%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestAddFastqs::test_adding_all_r2 PASSED                                                                                           [ 21%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestAddFastqs::test_adding_all_r1_and_r2 PASSED                                                                                    [ 24%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestAddFastqs::test_adding_per_sample_r1_fastqs PASSED                                                                             [ 26%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestAddFastqs::test_adding_per_sample_r2_fastqs PASSED                                                                             [ 29%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestAddFastqs::test_assert_equal_number_fastqs PASSED                                                                              [ 31%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestAddFastqs::test_assert_found_fastqs PASSED                                                                                     [ 34%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestAddOtherInputs::test_adding_sample_name PASSED                                                                                 [ 36%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestAddOtherInputs::test_adding_sample_prefix PASSED                                                                               [ 39%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestAddOtherInputs::test_adding_project_id PASSED                                                                                  [ 41%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestAddOtherInputs::test_adding_project_name PASSED                                                                                [ 43%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestAddOtherInputs::test_adding_parent_out_dir PASSED                                                                              [ 46%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestAddOtherInputs::test_adding_analysis_1_out_dir PASSED                                                                          [ 48%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestGetDependentJobs::test_per_sample_w_per_run_dependent_job PASSED                                                               [ 51%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestGetDependentJobs::test_per_run_get_analysis_1_jobs PASSED                                                                      [ 53%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestGetDependentJobs::test_per_run_get_all_jobs PASSED                                                                             [ 56%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestLinkInputsToOutputs::test_adding_all_analysis_1 PASSED                                                                         [ 58%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestLinkInputsToOutputs::test_adding_one_sample_analysis_1 PASSED                                                                  [ 60%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestLinkInputsToOutputs::test_parse_output_of_per_run_job PASSED                                                                   [ 63%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestPopulateOutputDirConfig::test_populate_app_output_dirs PASSED                                                                  [ 65%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestPopulateOutputDirConfig::test_populate_workflow_output_dirs PASSED                                                             [ 68%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestPopulateOutputDirConfig::test_not_replacing_hard_coded_paths PASSED                                                            [ 70%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestFilterJobOutputsDict::test_filter_job_outputs_dict_one_pattern PASSED                                                          [ 73%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestFilterJobOutputsDict::test_filter_multiple_patterns PASSED                                                                     [ 75%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestCheckInputClasses::test_array_input_with_single_dict_given PASSED                                                              [ 78%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestCheckInputClasses::test_file_input_with_array_length_one_given PASSED                                                          [ 80%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestCheckInputClasses::test_file_input_with_array_length_over_one PASSED                                                           [ 82%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestCheckAllInputs::test_find_unparsed_input PASSED                                                                                [ 85%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestCheckAllInputs::test_find_unparsed_analysis PASSED                                                                             [ 87%]
resources/home/dnanexus/run_workflows/tests/test_run_workflows.py::test_parse_sample_sheet PASSED                                                                                                   [ 90%]
resources/home/dnanexus/run_workflows/tests/test_run_workflows.py::test_parse_run_info_xml PASSED                                                                                                   [ 92%]
resources/home/dnanexus/run_workflows/tests/test_run_workflows.py::TestMatchSamplesToAssays::test_return_single_assay PASSED                                                                        [ 95%]
resources/home/dnanexus/run_workflows/tests/test_run_workflows.py::TestMatchSamplesToAssays::test_raise_assertion_error_on_mixed_assays PASSED                                                      [ 97%]
resources/home/dnanexus/run_workflows/tests/test_run_workflows.py::TestMatchSamplesToAssays::test_raise_assertion_error_on_sample_w_no_assay_code_match PASSED                                      [100%]

=========================================================================================== 41 passed in 1.44s ============================================================================================
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5)

### CODE REVIEW

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 6 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 1 of 2 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1 and @mattgarner)

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, 1 of 2 files at r7, 1 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5)* status: all files reviewed, 5 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[`resources/home/dnanexus/run_workflows/tests/test_manage_dict.py` line 284 at r8](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5#-NDn9HCRAgB5c-s3Z2as:-NDn9HCS7NwU2UWJcek2:b45h) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/95c6204df74abae5fb9b7eda832e598f5500b1c8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L284)):*
> ```Python
>     def test_adding_all_r2(self):
>         """
>         Test adding R2 fastqs from all samples as input where INPUT-R1 given
> ```





_Suggestion:_
```Python
2
```
___
*[`resources/home/dnanexus/run_workflows/tests/test_manage_dict.py` line 292 at r8](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5#-NDn9VlwERhVRPy1JyJx:-NDn9VlwERhVRPy1JyJy:b45h) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/95c6204df74abae5fb9b7eda832e598f5500b1c8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L292)):*
> ```Python
>             fastq_details=self.fastq_details
>         )
>         output_R1_fastqs = output['stage-G0qpXy0433Gv75XbPJ3xj8jV.reads2_fastqgzs']
> ```





_Suggestion:_
```Python
2
```
___
*[`resources/home/dnanexus/run_workflows/tests/test_manage_dict.py` line 301 at r8](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5#-NDn9YEf5lVLkBz4cgit:-NDn9YEf5lVLkBz4cgiu:undefined) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/95c6204df74abae5fb9b7eda832e598f5500b1c8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L301)):*
> ```Python
>         ]
> 
>         assert output_R1_fastqs == correct_R2_fastqs, (
> ```





_Suggestion:_
```Python
2
```
___
*[`resources/home/dnanexus/run_workflows/tests/test_manage_dict.py` line 622 at r8](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5#-NDnBedO-2T_ss0YpasX:-NDnBedO-2T_ss0YpasY:b-uvj1t4) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/95c6204df74abae5fb9b7eda832e598f5500b1c8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L622)):*
> ```Python
> 
> 
> class TestLinkInputsToOutputs():
> ```

Note to self - continue from here



_Code quote:_
```Python
class TestLinkInputsToOutputs():
```

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5)* status: all files reviewed, 5 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[`resources/home/dnanexus/run_workflows/tests/test_manage_dict.py` line 284 at r8](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5#-NDn9HCRAgB5c-s3Z2as:-NDnDWi0-GSzXjnlKfzy:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/95c6204df74abae5fb9b7eda832e598f5500b1c8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L284)):*
> ```Python
>     def test_adding_all_r2(self):
>         """
>         Test adding R2 fastqs from all samples as input where INPUT-R1 given
> ```

Done.
___
*[`resources/home/dnanexus/run_workflows/tests/test_manage_dict.py` line 292 at r8](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5#-NDn9VlwERhVRPy1JyJx:-NDnDbtG8NiXQCPp_DZh:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/95c6204df74abae5fb9b7eda832e598f5500b1c8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L292)):*
> ```Python
>             fastq_details=self.fastq_details
>         )
>         output_R1_fastqs = output['stage-G0qpXy0433Gv75XbPJ3xj8jV.reads2_fastqgzs']
> ```

Done.
___
*[`resources/home/dnanexus/run_workflows/tests/test_manage_dict.py` line 301 at r8](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5#-NDn9YEf5lVLkBz4cgit:-NDnDcyz-ko6DhvD59gK:by7yt83) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/95c6204df74abae5fb9b7eda832e598f5500b1c8/resources/home/dnanexus/run_workflows/tests/test_manage_dict.py#L301)):*
> ```Python
>         ]
> 
>         assert output_R1_fastqs == correct_R2_fastqs, (
> ```

I really did a bad copy paste job there.

Done

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @JasonLing95 and @mattgarner)

___
*[`resources/home/dnanexus/run_workflows/utils/dx_requests.py` line 76 at r7](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5#-NDhuVWIE6SDPuYla0PM:-NDnKqCPB2iLyLpxlTQg:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/0496553f48eab5704db308fc3c95c053cfe3bf02/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L76)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, 1 of 1 files at r3, 1 of 1 files at r4, 3 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @JasonLing95, @jethror1, and @mattgarner)

___
*[`resources/home/dnanexus/run_workflows/utils/manage_dict.py` line 379 at r8](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5#-NDnMUjx0_c8aERVWy90:-NDnMUjx0_c8aERVWy91:b5t4bpa) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/95c6204df74abae5fb9b7eda832e598f5500b1c8/resources/home/dnanexus/run_workflows/utils/manage_dict.py#L379)):*
> ```Python
>                     # run and not in the samples job dict => check if
>                     # it is in the main job_outputs_dict keys
>                     job = job_outputs_dict_copy.get(analysis_id)
> ```

sample is optional. If it's not set then job_outputs_dict_copy is not created.

Therefore if dependent analyses is True but samples is False, then job_outputs_dict_copy won't exist here



_Code quote:_
```Python
job_outputs_dict_copy
```

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @JasonLing95 and @mattgarner)

___
*[`resources/home/dnanexus/run_workflows/utils/manage_dict.py` line 379 at r8](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5#-NDnMUjx0_c8aERVWy90:-NDnZqi61vFLBGFURj8U:b-487ws2) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/95c6204df74abae5fb9b7eda832e598f5500b1c8/resources/home/dnanexus/run_workflows/utils/manage_dict.py#L379)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

sample is optional. If it's not set then job_outputs_dict_copy is not created.

Therefore if dependent analyses is True but samples is False, then job_outputs_dict_copy won't exist here
</blockquote></details>

I don't _think_ it would ever reach here if sample was False, the `job_outputs_dict` looks like this:
```
job_outputs_dict = {
        '2207155-22207Z0091-1-BM-MPD-MYE-M-EGG2': {
            'analysis_1': 'analysis-GGjgz0j4Bv4P8yqJGp9pyyv2',
            'analysis_3': 'job-GGjgyX04Bv44Vz151GGzFKgP'
        },
        'Oncospan-158-1-AA1-BBB-MYE-U-EGG2': {
            'analysis_1': 'analysis-GGjgz004Bv4P8yqJGp9pyyqb',
            'analysis_3': 'job-GGp69xQ4Bv45bk0y4kyVqvJ1'
        },
        'analysis_2': 'job-GGjgz1j4Bv48yF89GpZ6zkGz'
    }
```

where each job that is run per sample is in a sub dict of that sample ID to the analysis ID (analysis_1 and analysis_3) and any run per run in the root level (analysis_3).

If sample is False then when `search()` is called it is provided with the whole dict, so if searching for analysis_X it will find something.

I added this in because if sample is set then it searches just that samples jobs, but if it were dependent on a per run job (i.e analysis_2) it would not be in the dictionary it was searching, so would not find anything.

I guess there could be cases where a dependent analysis_X doesn't exist in the job outputs dict (likely through user error or maybe jobs that are optional and don't get launched?), it would drop into here and then we'd get a `NameError` raised as the variable isn't defined which isn't ideal.

I've now changed this to get a separate dict of just the per run jobs outside of sample dependent block, then search this if no jobs are found when searching the full job outputs dict.

Added couple more unit tests with an analysis_ that doesn't exist to show it works as intended:
```
jethro@jethro-T490:~/Projects/eggd_conductor$ python3 -m pytest -vv resources/home/dnanexus/run_workflows/tests/test_manage_dict.py -k "TestGetDependentJobs"
========================================================================================================== test session starts ==========================================================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/jethro/Projects/eggd_conductor
plugins: Faker-14.0.0, mock-3.9.0, cov-4.0.0
collected 38 items / 33 deselected / 5 selected                                                                                                                                                                                         

resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestGetDependentJobs::test_per_sample_w_per_run_dependent_job PASSED                                                                                             [ 20%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestGetDependentJobs::test_per_run_get_analysis_1_jobs PASSED                                                                                                    [ 40%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestGetDependentJobs::test_per_run_get_all_jobs PASSED                                                                                                           [ 60%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestGetDependentJobs::test_absent_analysis_does_not_raise_error PASSED                                                                                           [ 80%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestGetDependentJobs::test_absent_analysis_does_not_raise_error_per_sample PASSED                                                                                [100%]

=================================================================================================== 5 passed, 33 deselected in 0.16s ====================================================================================================
```

**Review by mattgarner — APPROVED** [review]
> Reviewed 9 of 9 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

___
*[`resources/home/dnanexus/run_workflows/utils/manage_dict.py` line 379 at r8](https://reviewable.io/reviews/eastgenomics/eggd_conductor/5#-NDnMUjx0_c8aERVWy90:-NEAcQbaDwgpN0J76CWj:b-tmzg4w) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/95c6204df74abae5fb9b7eda832e598f5500b1c8/resources/home/dnanexus/run_workflows/utils/manage_dict.py#L379)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I don't _think_ it would ever reach here if sample was False, the `job_outputs_dict` looks like this:
```
job_outputs_dict = {
        '2207155-22207Z0091-1-BM-MPD-MYE-M-EGG2': {
            'analysis_1': 'analysis-GGjgz0j4Bv4P8yqJGp9pyyv2',
            'analysis_3': 'job-GGjgyX04Bv44Vz151GGzFKgP'
        },
        'Oncospan-158-1-AA1-BBB-MYE-U-EGG2': {
            'analysis_1': 'analysis-GGjgz004Bv4P8yqJGp9pyyqb',
            'analysis_3': 'job-GGp69xQ4Bv45bk0y4kyVqvJ1'
        },
        'analysis_2': 'job-GGjgz1j4Bv48yF89GpZ6zkGz'
    }
```

where each job that is run per sample is in a sub dict of that sample ID to the analysis ID (analysis_1 and analysis_3) and any run per run in the root level (analysis_3).

If sample is False then when `search()` is called it is provided with the whole dict, so if searching for analysis_X it will find something.

I added this in because if sample is set then it searches just that samples jobs, but if it were dependent on a per run job (i.e analysis_2) it would not be in the dictionary it was searching, so would not find anything.

I guess there could be cases where a dependent analysis_X doesn't exist in the job outputs dict (likely through user error or maybe jobs that are optional and don't get launched?), it would drop into here and then we'd get a `NameError` raised as the variable isn't defined which isn't ideal.

I've now changed this to get a separate dict of just the per run jobs outside of sample dependent block, then search this if no jobs are found when searching the full job outputs dict.

Added couple more unit tests with an analysis_ that doesn't exist to show it works as intended:
```
jethro@jethro-T490:~/Projects/eggd_conductor$ python3 -m pytest -vv resources/home/dnanexus/run_workflows/tests/test_manage_dict.py -k "TestGetDependentJobs"
========================================================================================================== test session starts ==========================================================================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/jethro/Projects/eggd_conductor
plugins: Faker-14.0.0, mock-3.9.0, cov-4.0.0
collected 38 items / 33 deselected / 5 selected                                                                                                                                                                                         

resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestGetDependentJobs::test_per_sample_w_per_run_dependent_job PASSED                                                                                             [ 20%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestGetDependentJobs::test_per_run_get_analysis_1_jobs PASSED                                                                                                    [ 40%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestGetDependentJobs::test_per_run_get_all_jobs PASSED                                                                                                           [ 60%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestGetDependentJobs::test_absent_analysis_does_not_raise_error PASSED                                                                                           [ 80%]
resources/home/dnanexus/run_workflows/tests/test_manage_dict.py::TestGetDependentJobs::test_absent_analysis_does_not_raise_error_per_sample PASSED                                                                                [100%]

=================================================================================================== 5 passed, 33 deselected in 0.16s ====================================================================================================
```

</blockquote></details>

Great, thanks for the detailed explanation :+1:

**Pull request merged**
