### PR TITLE
v1.4.0 - wait on done

### PR DESCRIPTION
**Pull request by jethror1**
- add in ability to hold conductor until a job(s) complete before moving on to launch next steps through adding optional `'hold'` key to the config, will be used for holding when launching eggd_TSO500 to enable launching downstream reports workflows. This is similar behaviour to how Nextflow etc has an always running head node.
- example job here `'hold': true` to a per_sample: true analysis: https://platform.dnanexus.com/panx/projects/GbvyYZj4zQV7xXvj49XBXF4V/monitor/job/GbxJvfj4zQV5G6fX2f72f927

image

- example job of `'hold': true` added to a per_run step: https://platform.dnanexus.com/panx/projects/GbvyYZj4zQV7xXvj49XBXF4V/monitor/job/GbxK1zj4zQVP0j7FyqvYQJ70

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/92)

### CODE REVIEW

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/92)* status: all files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`README.md` line 129 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/92#-NlcDNwL7fRM4Cpovvsc:-NlcDNwL7fRM4Cpovvsd:b-8z7epd) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/bedd49ac0ed6cb631c9192ec15cc1d5676836930/README.md#L129)):*
> ```Markdown
> - `sample_name_delimeter` (str): string to split sample name on and pass to where `INPUT-SAMPLE-NAME` is used. Useful for passing as input where full sample name is not wanted (i.e. for displaying in a report)
> - `extra_args` (dict): mapping of [additional paramaters][dx-run-parameters] to pass to underlying API call for running dx analysis (i.e priority, cost_limit, instance_type) - see below for example formatting
> - `hold` (boolean): controls if to hold conductor until all jobs for the given executable complete before attempting to launch the next analysis steps. This may be used when downstream analysis may need to split out an array of output files from an upstream job, instead of taking the full array as input.
> ```

controls whether?
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 582 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/92#-NlcDVDpBq71kYSRogyI:-NlcDVDpBq71kYSRogyJ:b-ap0lj0) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/bedd49ac0ed6cb631c9192ec15cc1d5676836930/resources/home/dnanexus/run_workflows/run_workflows.py#L582)):*
> ```Python
> 
>             # loop over samples and call app / workflow
>             for idx, sample in enumerate(sample_list):
> ```

you can also do `enumerate(sample_list, 1)` rather than adding 1 every time

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/92)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`README.md` line 129 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/92#-NlcDNwL7fRM4Cpovvsc:-NlcVHaX-0uhv8QwxZki:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/bedd49ac0ed6cb631c9192ec15cc1d5676836930/README.md#L129)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

controls whether?
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/92)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 582 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/92#-NlcDVDpBq71kYSRogyI:-NlcVJJo8IeBh0_qdjEO:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/bedd49ac0ed6cb631c9192ec15cc1d5676836930/resources/home/dnanexus/run_workflows/run_workflows.py#L582)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

you can also do `enumerate(sample_list, 1)` rather than adding 1 every time
</blockquote></details>

Done.

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/92)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
