### PR TITLE
More changes for v1 (maybe nearly finally there hopefully)

### PR DESCRIPTION
**Pull request by jethror1**
## Summary

Refactoring of all code from previous work for v1, migration of most bash code into Python for easier unit testing and rewriting of various methods to be simpler.

Changed to running from a single fixed config file with auth tokens and a DNAnexus `project:path` to a directory of all assay config files, where the highest for each assay is used based on a `assay_code` and `version` present in the top level of the config. 

Example app config: https://github.com/eastgenomics/eggd_conductor/blob/new_dev/example/eggd_conductor.cfg
Example populated assay json config: https://github.com/eastgenomics/eggd_conductor/blob/new_dev/example/example_populated_config.json

**Execution flow summary**:
- `eggd_conductor.sh` runs, sets environment variables (those from app cfg file), sends a starting Slack notification and parses samplesheet from the sentinel file
- `run_workflows.py` is the main entry point for launching all jobs
- configs are first gathered and samples matched to appropriate configs (currently only handles runs of single assays)
- bcl2fastq is run and the app held until it completes unless a bcl2fastq job ID is passed or analysis is starting from fastqs
- config is parsed and for each 'executable' defined (app or workflow) the following is done:
  - output directories set in `ManageDict().populate_output_dir_config()`
  - fastqs added in `ManageDict().add_fastqs()`
  - jobs that the current executable is dependent on finishing parsed in `ManageDict().get_dependent_jobs()`
  - other inputs (such as placeholders like `INPUT-dx_project_id` to pass the project ID as an input) are parsed in `ManageDict().add_other_inputs()`
  - inputs that are an output of a previously launched job are parsed in `ManageDict().link_inputs_to_outputs()`
  - jobs launched by `DXExecute.call_dx_run()`
- if all jobs successfully launched, a Slack notification is sent with a link to the jobs and the eggd_conductor job tagged with the URL to link to downstream analysis

## New scripts
- `manage_dict.py`: all methods related to parsing input and output dictionaries for running jobs
- `dx_requests.py`: all DNAnexus related methods, split to those for starting jobs (`DXExecute()`) and those for generic handling of dx related things (`DXManage()`)
- `utils.py`: other utility methods such as those for Slack notifications

## Testing
Started writing of unit tests here for dict methods: https://github.com/eastgenomics/eggd_conductor/tree/new_dev/resources/home/dnanexus/run_workflows/tests
More to be added before v1.0.0 release ready...

## Example Slack notifications
- Analysis starting
  - includes URL to eggd_conductor job
image

- All jobs successfully started
   - includes URL to monitor tab of analysis project where jobs have been launched
image

- Error occurred from `run_workflows.py` that has been handled (i.e. intentional raising of an `AssertionError` or `RunTimeError` etc)
image

- Unhandled error occurred  in `run_workflows.py` that is caught in the bash script
  - in these instances the Python traceback is parsed from `dx_stderr` and added to the notification

image

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)

### CODE REVIEW

**Review by mattgarner — COMMENTED** [review]
> Reviewed 26 of 37 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: 26 of 37 files reviewed, all discussions resolved (waiting on @JasonLing95)

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: 26 of 37 files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`src/eggd_conductor.sh` line 119 at r3](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCvf3n84-9IttCbLmNf:-NCvf3n84-9IttCbLmNg:b-kfqz84) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/75fff8c025ba887157a49156b5b6ec7095d2ab7e/src/eggd_conductor.sh#L119)):*
> ```Shell
>         mkdir ./first_tar_dir
>         tar -xzf first_tar.tar.gz -C ./first_tar_dir
>         SAMPLESHEET=$(find ./first_tar_dir -regextype posix-extended  -iregex '.*sample[-_ ]?sheet.csv$')
> ```

Should the regex also match camelcase versions of samplesheet?



_Code quote:_
```Shell
.*sample[-_ ]?sheet.csv$
```
___
*[`src/eggd_conductor.sh` line 306 at r3](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCvjFNH0V9Ggj-suJjp:-NCvjFNI3iD9gTDxZDRa:brntrxq) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/75fff8c025ba887157a49156b5b6ec7095d2ab7e/src/eggd_conductor.sh#L306)):*
> ```Shell
> 
>     # tag conductor job with downstream project used for analysis
>     dx tag "$PARENT_JOB_ID" "$conductor_job_url"
> ```

$PARENT_JOB_ID = $DX_JOB_ID = the id of this conductor job
$conductor_job_url = the URL which points to this conductor job

Isn't this going to tag this job with its own URL, not with the downstream analysis project it creates. Very possible that I'm being dumb.



_Code quote:_
```Shell
dx tag "$PARENT_JOB_ID" "$conductor_job_url"
```

**Review by JasonLing95 — CHANGES_REQUESTED** [review]
> Reviewed 37 of 37 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: all files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[`README.md` line 85 at r3](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCxpAmS0jszdFHeI4nT:-NCxpAmS0jszdFHeI4nU:bs3002f) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/75fff8c025ba887157a49156b5b6ec7095d2ab7e/README.md#L85)):*
> ```Markdown
> - `per_sample` (boolean): if to run the executable on each sample individually, or as one multi-sample job
> - `process_fastqs` (boolean): if the executable requires fastqs passing
> - `inputs` (dict): this forms the input dictionary passed to the call to dx api to trigger the running of the executable, more details may be found [here](dx-run-url). See below for structure and available inputs.
> ```

this link is not working



_Code quote:_
```Markdown
[here](dx-run-url)
```
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 123 at r3](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCxqbEo2S2qW_ZFo1Z2:-NCxqbEo2S2qW_ZFo1Z3:b-mz5qsk) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/75fff8c025ba887157a49156b5b6ec7095d2ab7e/resources/home/dnanexus/run_workflows/run_workflows.py#L123)):*
> ```Python
>     for code in all_config_assay_codes:
>         for sample in all_samples:
>             if code in sample:
> ```

is there only one 'right' code so once we found the code in sample, we can break from the for loop?



_Code quote:_
```Python
            if code in sample:
                assay_to_samples[code].append(sample)
```

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: 35 of 37 files reviewed, 4 unresolved discussions (waiting on @JasonLing95 and @mattgarner)

___
*[`README.md` line 85 at r3](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCxpAmS0jszdFHeI4nT:-NCyTzHRBL_2MHuP3FQ3:b-7ql1td) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/75fff8c025ba887157a49156b5b6ec7095d2ab7e/README.md#L85)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

this link is not working
</blockquote></details>

fixed
___
*[`src/eggd_conductor.sh` line 119 at r3](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCvf3n84-9IttCbLmNf:-NCyRik7EQwKCG37l_PS:b-b822y3) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/75fff8c025ba887157a49156b5b6ec7095d2ab7e/src/eggd_conductor.sh#L119)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Should the regex also match camelcase versions of samplesheet?
</blockquote></details>

`-iregex`  handles that and sets it to case insensitive regex:

```
$ ls
samplesheet.csv  SampleSheet.csv

$ find ./ -regextype posix-extended  -iregex '.*sample[-_ ]?sheet.csv$'
./SampleSheet.csv
./samplesheet.csv
```
___
*[`src/eggd_conductor.sh` line 306 at r3](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCvjFNH0V9Ggj-suJjp:-NCySRPp1LXP5jcZiVN_:bc39t1h) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/75fff8c025ba887157a49156b5b6ec7095d2ab7e/src/eggd_conductor.sh#L306)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

$PARENT_JOB_ID = $DX_JOB_ID = the id of this conductor job
$conductor_job_url = the URL which points to this conductor job

Isn't this going to tag this job with its own URL, not with the downstream analysis project it creates. Very possible that I'm being dumb.
</blockquote></details>

good catch,  have changed it to be the same as what is in the slack success message
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 123 at r3](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCxqbEo2S2qW_ZFo1Z2:-NCySjxO79ZD-Cu17Ba6:b-a2fu3z) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/75fff8c025ba887157a49156b5b6ec7095d2ab7e/resources/home/dnanexus/run_workflows/run_workflows.py#L123)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

is there only one 'right' code so once we found the code in sample, we can break from the for loop?
</blockquote></details>

the inner loop is over the samples so no, still want to go to the end as well to ensure we find only one assay match for each sample, and that all samples are only for one assay atm. There's only 20-50 samples and at most there will be 5 configs to begin with, so not a big issue on how many times it has to loop

**Review by JasonLing95 — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: 36 of 37 files reviewed, 3 unresolved discussions (waiting on @JasonLing95 and @mattgarner)

**Review by mattgarner — COMMENTED** [review]
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: 36 of 37 files reviewed, all discussions resolved (waiting on @JasonLing95)

___
*[`src/eggd_conductor.sh` line 119 at r3](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCvf3n84-9IttCbLmNf:-NCzLViT7z-ECVTpRuKU:b-2c2iba) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/75fff8c025ba887157a49156b5b6ec7095d2ab7e/src/eggd_conductor.sh#L119)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

`-iregex`  handles that and sets it to case insensitive regex:

```
$ ls
samplesheet.csv  SampleSheet.csv

$ find ./ -regextype posix-extended  -iregex '.*sample[-_ ]?sheet.csv$'
./SampleSheet.csv
./samplesheet.csv
```
</blockquote></details>

I must be too used to seeing `-isomething` in DNAnexus.
___
*[`src/eggd_conductor.sh` line 306 at r3](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCvjFNH0V9Ggj-suJjp:-NCzLQFA7CvkQBQBEXxU:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/75fff8c025ba887157a49156b5b6ec7095d2ab7e/src/eggd_conductor.sh#L306)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

good catch,  have changed it to be the same as what is in the slack success message
</blockquote></details>

Done

**Review by mattgarner — COMMENTED** [review]
> Reviewed 4 of 37 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Review by JasonLing95 — APPROVED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 37 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: all files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 17 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCzNbt-6vwAedXjDhXG:-NCzNbt-6vwAedXjDhXH:ba3dfna) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/cfe0e5b6af1f7d6b7573c0a29e73bf2654f4ea7c/resources/home/dnanexus/run_workflows/run_workflows.py#L17)):*
> ```Python
>     - test mode - DONE
>     - log jobs started in case of failing to start some and terminate all - DONE
>     - tag conductor job with link to downstream project jobs and bcl2fastq job
> ```

Remove?



_Code quote:_
```Python
TODO
    - slack notifications - DONE
    - test mode - DONE
    - log jobs started in case of failing to start some and terminate all - DONE
    - tag conductor job with link to downstream project jobs and bcl2fastq job
```
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 139 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCzOaqB4eCV4AgqOxcb:-NCzOaqB4eCV4AgqOxcc:ba3dfna) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/cfe0e5b6af1f7d6b7573c0a29e73bf2654f4ea7c/resources/home/dnanexus/run_workflows/run_workflows.py#L139)):*
> ```Python
>         )
> 
>     # TODO: remove - just for testing
> ```

Remove?



_Code quote:_
```Python
# TODO: remove - just for testing
```
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 426 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCzPvMX79w73WYUe7Ri:-NCzPvMX79w73WYUe7Rj:bti8765) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/cfe0e5b6af1f7d6b7573c0a29e73bf2654f4ea7c/resources/home/dnanexus/run_workflows/run_workflows.py#L426)):*
> ```Python
> 
>         # TODO: check if this is needed anymore and how to handle
>         # passing app specific output dirs (if needed)
> ```

Does this need discussion?



_Code quote:_
```Python
        # TODO: check if this is needed anymore and how to handle
        # passing app specific output dirs (if needed)
```

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: 36 of 37 files reviewed, 3 unresolved discussions (waiting on @JasonLing95, @jethror1, and @mattgarner)

___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 17 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCzNbt-6vwAedXjDhXG:-NCzRgeJAJRCc2cByQe9:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/cfe0e5b6af1f7d6b7573c0a29e73bf2654f4ea7c/resources/home/dnanexus/run_workflows/run_workflows.py#L17)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 139 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCzOaqB4eCV4AgqOxcb:-NCzRIp2E2xZaVa1sUDH:b-ftj3r8) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/cfe0e5b6af1f7d6b7573c0a29e73bf2654f4ea7c/resources/home/dnanexus/run_workflows/run_workflows.py#L139)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

will do, think I might make it an extra testing arg as its useful to only spin up a couple of jobs

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 37 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: 36 of 37 files reviewed, 4 unresolved discussions (waiting on @JasonLing95, @jethror1, and @mattgarner)

___
*[`resources/home/dnanexus/run_workflows/utils/manage_dict.py` line 79 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCzRY3nADFDKxI28cXt:-NCzRY3nADFDKxI28cXu:bb7phvt) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/cfe0e5b6af1f7d6b7573c0a29e73bf2654f4ea7c/resources/home/dnanexus/run_workflows/utils/manage_dict.py#L79)):*
> ```Python
>             id of DNAnexus object to link input to
>         search_key : bool
>             determines it to search dictionary keys or values
> ```

typo



_Code quote:_
```Python
it
```

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: 31 of 37 files reviewed, 4 unresolved discussions (waiting on @JasonLing95, @jethror1, and @mattgarner)

___
*[`resources/home/dnanexus/run_workflows/utils/manage_dict.py` line 79 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCzRY3nADFDKxI28cXt:-ND-dmnA2qMDlCq-HwjD:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/cfe0e5b6af1f7d6b7573c0a29e73bf2654f4ea7c/resources/home/dnanexus/run_workflows/utils/manage_dict.py#L79)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 139 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCzOaqB4eCV4AgqOxcb:-ND-bm2T0qj2Nz3xXZX5:b-rqai1) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/cfe0e5b6af1f7d6b7573c0a29e73bf2654f4ea7c/resources/home/dnanexus/run_workflows/run_workflows.py#L139)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

will do, think I might make it an extra testing arg as its useful to only spin up a couple of jobs
</blockquote></details>

have now made this an extra argument so its not hardcoded
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 426 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCzPvMX79w73WYUe7Ri:-ND-bpzG2s0UqB4SD1ME:bijsggv) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/cfe0e5b6af1f7d6b7573c0a29e73bf2654f4ea7c/resources/home/dnanexus/run_workflows/run_workflows.py#L426)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Does this need discussion?
</blockquote></details>

not really sure, not for v1 I don't think but I'm going to leave it for future me to remember where it is as it may need some thought.

The only thing (I think) that requires a directory passing as input is multiqc, which can be done by specifying the parent dir of each individual app output dir (in our case it would be the `OUT-FOLDER` key), from the 'Structuring the output-dirs dictionary' from the readme:

```
- `OUT-FOLDER`: will be in the format of `/output/{assay_name}_{timestamp}/`
- `APP-NAME`: will use the name for the given app id from a `dx describe` call
- `WORKFLOW-NAME`: will use the name for the given workflow id from a `dx describe` call
- `STAGE-NAME`: will use the name for the stage of the given workflow id from a `dx describe` call
```
for apps we would have it as `"/OUT-FOLDER/APP-NAME"` and for workflows as `"/OUT-FOLDER/STAGE-NAME"`.


Example populated config which is pretty much what I have used for testing is here: 

https://github.com/eastgenomics/eggd_conductor/blob/new_dev/example/example_populated_config.json

and example output in project:

https://platform.dnanexus.com/panx/projects/GB3jx784Bv40j3Zx4P5vvbzQ/data/output/MYE-220926_1031

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: 30 of 37 files reviewed, 4 unresolved discussions (waiting on @JasonLing95, @jethror1, and @mattgarner)

___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 426 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCzPvMX79w73WYUe7Ri:-ND24IX66kfNQVXAPeHT:biekbm9) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/cfe0e5b6af1f7d6b7573c0a29e73bf2654f4ea7c/resources/home/dnanexus/run_workflows/run_workflows.py#L426)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

not really sure, not for v1 I don't think but I'm going to leave it for future me to remember where it is as it may need some thought.

The only thing (I think) that requires a directory passing as input is multiqc, which can be done by specifying the parent dir of each individual app output dir (in our case it would be the `OUT-FOLDER` key), from the 'Structuring the output-dirs dictionary' from the readme:

```
- `OUT-FOLDER`: will be in the format of `/output/{assay_name}_{timestamp}/`
- `APP-NAME`: will use the name for the given app id from a `dx describe` call
- `WORKFLOW-NAME`: will use the name for the given workflow id from a `dx describe` call
- `STAGE-NAME`: will use the name for the stage of the given workflow id from a `dx describe` call
```
for apps we would have it as `"/OUT-FOLDER/APP-NAME"` and for workflows as `"/OUT-FOLDER/STAGE-NAME"`.


Example populated config which is pretty much what I have used for testing is here: 

https://github.com/eastgenomics/eggd_conductor/blob/new_dev/example/example_populated_config.json

and example output in project:

https://platform.dnanexus.com/panx/projects/GB3jx784Bv40j3Zx4P5vvbzQ/data/output/MYE-220926_1031


</blockquote></details>

actually this comment was in the wrong place (and I think I deleted the code that was here), this is just saving the name of the app/workflow to name the job when called, have now removed the comment

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r6, 1 of 1 files at r8, 1 of 1 files at r9, 2 of 2 files at r10, 1 of 2 files at r11.
> Dismissed @jethror1 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: 36 of 37 files reviewed, 1 unresolved discussion (waiting on @JasonLing95 and @jethror1)

___
*[`resources/home/dnanexus/run_workflows/utils/manage_dict.py` line 185 at r11](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-ND2Qu-m7-NGr0rBJpil:-ND2Qu-m7-NGr0rBJpim:bplerv9) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/d17e70428566d6060ec45e61d47cafc6b5e15ceb/resources/home/dnanexus/run_workflows/utils/manage_dict.py#L185)):*
> ```Python
>         print(f'Found {len(r1_fastqs)} R1 fastqs & {len(r2_fastqs)} R2 fastqs')
> 
>         assert len(r1_fastqs) == len(r2_fastqs), Slack().send(
> ```

It's possible to have no R2s if single end sequencing. I think this is fine as it is since we don't do any single end, but need to keep it in mind if we ever do.



_Code quote:_
```Python
assert len(r1_fastqs) == len(r2_fastqs), Slack().send(
```
___
*[`resources/home/dnanexus/run_workflows/utils/manage_dict.py` line 409 at r11](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-ND2Txla2SA9GoqMWdlj:-ND2Txla2SA9GoqMWdlk:b-le2fye) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/d17e70428566d6060ec45e61d47cafc6b5e15ceb/resources/home/dnanexus/run_workflows/utils/manage_dict.py#L409)):*
> ```Python
>         PPRINT(input_dict)
> 
>         if analysis == "analysis_1":
> ```

Perhaps make it very clear in the readme that the first analysis must be tagged as `analysis_1`

If there were 2 initial workflows could we handle this?
i.e.

```
start------>end

1--\
    3--
2--/
```



_Code quote:_
```Python
if analysis == "analysis_1"
```
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 139 at r4](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-NCzOaqB4eCV4AgqOxcb:-ND2W1ZQEahlw8tRrEO3:bb6un1j) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/cfe0e5b6af1f7d6b7573c0a29e73bf2654f4ea7c/resources/home/dnanexus/run_workflows/run_workflows.py#L139)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

have now made this an extra argument so its not hardcoded
</blockquote></details>

Done

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: 36 of 37 files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`resources/home/dnanexus/run_workflows/utils/dx_requests.py` line 497 at r11](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-ND2Xmd_AaPMDnSDZdje:-ND2Xmd_AaPMDnSDZdjf:bo6bm4a) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/d17e70428566d6060ec45e61d47cafc6b5e15ceb/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L497)):*
> ```Python
>         """
>         dx_projects = list(dx.bindings.search.find_projects(
>             name=project_name, limit=1
> ```

Would it be better to return all matches and bail if >1 result? 

It is possible to have multiple dx projects with the same project name



_Code quote:_
```Python
limit=1
```

**Review by mattgarner — COMMENTED** [review]
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @jethror1)

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2)* status: 34 of 37 files reviewed, 2 unresolved discussions (waiting on @JasonLing95 and @mattgarner)

___
*[`resources/home/dnanexus/run_workflows/utils/dx_requests.py` line 497 at r11](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-ND2Xmd_AaPMDnSDZdje:-ND2c1EH9wVbO2ezYlUu:b-my6n6m) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/d17e70428566d6060ec45e61d47cafc6b5e15ceb/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L497)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Would it be better to return all matches and bail if >1 result? 

It is possible to have multiple dx projects with the same project name
</blockquote></details>

good point, have changed
___
*[`resources/home/dnanexus/run_workflows/utils/manage_dict.py` line 185 at r11](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-ND2Qu-m7-NGr0rBJpil:-ND2_tLZ7GSSjsOyEjr1:bkgrn01) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/d17e70428566d6060ec45e61d47cafc6b5e15ceb/resources/home/dnanexus/run_workflows/utils/manage_dict.py#L185)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

It's possible to have no R2s if single end sequencing. I think this is fine as it is since we don't do any single end, but need to keep it in mind if we ever do.
</blockquote></details>

I can add a check if all fastqs (not just for the given sample) have no R2's then assume this is single ended?

```
# sense check we have R2 fastqs before across all samples (i.e.
# checking this isn't single end sequencing) before checking we
# have equal numbers
all_r2_fastqs = [x for x in fastq_details if 'R2_001.fastq' in x[1]]

if all_r2_fastqs:
    assert len(r1_fastqs) == len(r2_fastqs), Slack().send(
        f"Mismatched number of FastQs found.\n"
        f"R1: {r1_fastqs} \nR2: {r2_fastqs}"
    )
```
___
*[`resources/home/dnanexus/run_workflows/utils/manage_dict.py` line 409 at r11](https://reviewable.io/reviews/eastgenomics/eggd_conductor/2#-ND2Txla2SA9GoqMWdlj:-ND2Y6jX1xq6jb1IroZ0:b-gkk2a4) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/d17e70428566d6060ec45e61d47cafc6b5e15ceb/resources/home/dnanexus/run_workflows/utils/manage_dict.py#L409)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Perhaps make it very clear in the readme that the first analysis must be tagged as `analysis_1`

If there were 2 initial workflows could we handle this?
i.e.

```
start------>end

1--\
    3--
2--/
```
</blockquote></details>

yep, this is what happens for myeloid running all the single workflows and multi fastqc at the same time, in the example above you would have:
```
"executables": {
    "analysis_1": {
        ...
    },
    "analysis_2": {
        ...
    }
    "anaylsis_3": {
        ...
        depends_on: [analysis_1, analysis_2]
    }
}
```

so all jobs for analysis_1 and analysis_2 would be launched together, then analysis 3 jobs would wait on 1 and 2 to complete.

Have changed the read me a bit to describe using analysis_:

- `analysis`: the value must be written as `analysis_1`, where the number is the executable stage in the config (i.e for the first workflow / app this would be `analysis_1`, for the second `analysis_2`...). This determines the order of executables being launched and is used to link the outputs of one workflow / app to subsequent workflows / apps.


does this make sense?

**Pull request merged**
