### PR TITLE
v1.2.0 - improve config filtering

### PR DESCRIPTION
**Pull request by jethror1**
Update to accommodate mixed assay codes that will be coming with Epic and improve filtering of assay config files pulled from DNAnexus to only keep the highest version of each by the individual assay codes in the 'assay_code' field of the config files.

Main changes for this are in `dx_requests.py` with the new function `DXManage.filter_highest_config_version()`, this contains all the logic for filtering down all config files found to retain the highest version. Minor changes have then been made to `DXManage.get_json_configs()` so that this function does none of the version filtering, and changes in matching samples to assay config files needed in `run_workflows.py - match_samples_to_assays()`.

Other changes are minor comments, clear up some of the logging and updating the readme.

Unit tests have been added for `DXManage.filter_highest_config_version()`:

```
$ python3 -m pytest -v resources/home/dnanexus/run_workflows/tests/test_dx_requests.py 
================================================== test session starts ===================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/jethro/Projects/eggd_conductor
plugins: Faker-14.0.0, mock-3.9.0, cov-4.0.0
collected 4 items                                                                                                        

resources/home/dnanexus/run_workflows/tests/test_dx_requests.py::TestFilterHighestConfigVersion::test_correct_filtered_configs PASSED [ 25%]
resources/home/dnanexus/run_workflows/tests/test_dx_requests.py::TestFilterHighestConfigVersion::test_assert_raised_with_two_configs_of_same_version PASSED [ 50%]
resources/home/dnanexus/run_workflows/tests/test_dx_requests.py::TestFilterHighestConfigVersion::test_assert_raised_on_missing_assay_code PASSED [ 75%]
resources/home/dnanexus/run_workflows/tests/test_dx_requests.py::TestFilterHighestConfigVersion::test_assert_raised_on_missing_version PASSED [100%]

=================================================== 4 passed in 0.71s ====================================================
```

Tests for matching samples to assay configs:
```
$ python3 -m pytest -v resources/home/dnanexus/run_workflows/tests/test_run_workflows.py 
================================================== test session starts ===================================================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/jethro/Projects/eggd_conductor
plugins: Faker-14.0.0, mock-3.9.0, cov-4.0.0
collected 5 items                                                                                                        

resources/home/dnanexus/run_workflows/tests/test_run_workflows.py::test_parse_sample_sheet PASSED                  [ 20%]
resources/home/dnanexus/run_workflows/tests/test_run_workflows.py::test_parse_run_info_xml PASSED                  [ 40%]
resources/home/dnanexus/run_workflows/tests/test_run_workflows.py::TestMatchSamplesToAssays::test_return_single_assay PASSED [ 60%]
resources/home/dnanexus/run_workflows/tests/test_run_workflows.py::TestMatchSamplesToAssays::test_raise_assertion_error_on_mixed_assays PASSED [ 80%]
resources/home/dnanexus/run_workflows/tests/test_run_workflows.py::TestMatchSamplesToAssays::test_raise_assertion_error_on_sample_w_no_assay_code_match PASSED [100%]
```

Test job for a TSO500 run: https://platform.dnanexus.com/projects/GQ0xPyj49GgpqvxvQb6kF08y/monitor/job/GQ9Q7G849GgkYzzgz4z4kkb5

Test job for a myeloid run: https://platform.dnanexus.com/projects/GQ0xPyj49GgpqvxvQb6kF08y/monitor/job/GQ9Q3q049GgxyZFBFZ00bPjF

Test job for a myeloid run where a new config file was added with an additional assay code added to mimic expected behaviour when Epic is live: https://platform.dnanexus.com/projects/GQ0xPyj49GgpqvxvQb6kF08y/monitor/job/GQ9QGz849GgV3f5fk8YzzzXg

Top level of test myeloid 1.1.1 config file added with additional assay codes:
```
$ dx cat file-GQ9QGp84y1jKF0209p0qp998 | jq | head -n15
{
  "name": "Config for myeloid assay",
  "assay": "MYE",
  "assay_code": "EGG2|LAB1234|LAB5678",
  "version": "1.1.1",
  "details": "Includes main Uranus workflow, multi_fastqc, somalier workflow and multiQC",
  "changelog": {
    "v1.0.0": "Initial working version",
    "v1.1.0": "Updated main workflow to v1.11.0; updated multiQC app to v2.0.1 + config file and Docker image",
    "v1.1.1": "Added 2 new assay codes for transition to Epic testing, EGG2 kept for backwards compatibility"
  },
  "demultiplex": true,
  "users": {
    "org-emee_1": "CONTRIBUTE"
  },
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/56)

### CODE REVIEW

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
is the assay code taking the latest version of the config appropriate? let's say you have an EGG2 sample, would taking the latest config be appropriate?

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/56#-:-NQeLFHcDrtMXGmga0vG:b7h5i4z)* status: all files reviewed, 3 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`README.md` line 54 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/56#-NQeLh864ejZqJEPPGcR:-NQeLh864ejZqJEPPGcS:bqukv0u) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/1c9519e9b793ec75dc4d43d6f8082ffb4693f268/README.md#L54)):*
> ```Markdown
> 
> - `assay` (str): identifier of the assay the config is for (i.e. MYE, TSO500), will be used to name output directory, must be the same between versions for the same `assay_code`
> - `assay_code` (str): code(s) used to match against sample name to determine if the config is for the given sample. At runtime, all configs are pulled from `ASSAY_CONFIG_PATH` in DNAnexus, and the highest version for each code present is determined and kept to use for analysis. These assay codes are then used to match against sample names to determine which config file to use for analysis based on the presence of the code in the samplename. Multiple codes may be defined for one assay by seperating with a `|` (i.e. `'assay_code': 'LAB123|LAB456'`). This allows where a single config should be used for different codes, and handles having samples on a run with mixed codes but requiring the sample analysis.
> ```

sample name
separating
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 124 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/56#-NQeLxad2EEAtCBADM9L:-NQeLxad2EEAtCBADM9M:b-tofikt) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/1c9519e9b793ec75dc4d43d6f8082ffb4693f268/resources/home/dnanexus/run_workflows/run_workflows.py#L124)):*
> ```Python
> 
>     # for each sample check each assay code if it matches, then select the
>     # matching config with highest versiuon
> ```

version
___
*[`resources/home/dnanexus/run_workflows/utils/dx_requests.py` line 710 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/56#-NQeOIEPByvitfPKZs9I:-NQeOIEPByvitfPKZs9J:bvhm761) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/1c9519e9b793ec75dc4d43d6f8082ffb4693f268/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L710)):*
> ```Python
>                 current_config_code, {}).get('version', '0')
> 
>             if current_config_ver > highest_ver:
> ```

have you tested this with 1.2.0 vs 1.11.0 for example?
I'd use the packaging package for version comparison https://packaging.pypa.io/en/stable/version.html . It is used in Dias

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/56)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @JasonLing95 and @Yu-jinKim)

___
*[`README.md` line 54 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/56#-NQeLh864ejZqJEPPGcR:-NQegl7wDDGlYzmnKBTc:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/1c9519e9b793ec75dc4d43d6f8082ffb4693f268/README.md#L54)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

sample name
separating
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 124 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/56#-NQeLxad2EEAtCBADM9L:-NQegkfEC2Udt6ib6UqP:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/1c9519e9b793ec75dc4d43d6f8082ffb4693f268/resources/home/dnanexus/run_workflows/run_workflows.py#L124)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

version
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/run_workflows/utils/dx_requests.py` line 710 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/56#-NQeOIEPByvitfPKZs9I:-NQegnWAAMqibMwttw6r:b4jpqlo) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/1c9519e9b793ec75dc4d43d6f8082ffb4693f268/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L710)):*
10/10 catch:
```
>>> '1.2.0' > '1.11.0'
True
```

switched to using version for the comparing of versions here with same code, and then `packaging.version.parse` with  `max()` for selecting the highest version from the dict further down which maps assay_code : version. Also did the same in the sample to assay matching and added unit tests for this

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Review by JasonLing95 — COMMENTED** [review]
> Reviewed 3 of 8 files at r1, 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/56)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
