### PR TITLE
In 711 handle multiple configs - Part 8 (untested)

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- Ticket comment handling

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/132)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/132)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @Yu-jinKim)

___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 547 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/132#-O6zGbflAbupOnsdNGJU:-O6zGbflAbupOnsdNGJV:b-bnho12) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/5b94db83c4a1aa0e4b35d3e84c1b2eec735fac84/resources/home/dnanexus/run_workflows/run_workflows.py#L547)):*
> ```Python
>             else:
>                 Slack().send(
>                     f"Ticket {ticket['key']} has multiple assays: {assay_codes}"
> ```

here the only thing we send a Slack alert for is if the ticket assay field has more than one, so we don't catch if there's:
- no tickets
- too many tickets
- ticket assay doesn't match our assay config

I think it might be better to define an empty list of errors, then append error messages to each for any of the above then check at the end and send Slack alert if any found



_Code quote:_
```Python
                Slack().send(
                    f"Ticket {ticket['key']} has multiple assays: {assay_codes}"
```
___
*[`resources/home/dnanexus/run_workflows/utils/request_objects.py` line 231 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/132#-O6zHCiMESBFt5vp3pw_:-O6zHCiMESBFt5vp3pwa:bb7phvt) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/5b94db83c4a1aa0e4b35d3e84c1b2eec735fac84/resources/home/dnanexus/run_workflows/utils/request_objects.py#L231)):*
> ```Python
>             # aren't wanting to use Jira and continue
>             prettier_print(
>                 "No required Jira variables set in config, continuinung "
> ```

typo



_Code quote:_
```Python
continuinun
```

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/132)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Yu-jinKim)

___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 829 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/132#-O6zHt7I5znmqc3a-pnZ:-O6zHt7J7281NTURJ6fS:bb0vdgl) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/5b94db83c4a1aa0e4b35d3e84c1b2eec735fac84/resources/home/dnanexus/run_workflows/run_workflows.py#L829)):*
> ```Python
>                 f"{data['project'].describe().get('name').replace('project-', '')}/monitor/"
>             ),
>             ticket=data["ticket"]
> ```

what is data? don't you store the ticket ID in `dx_builder.config_to_samples` above?



_Code quote:_
```Python
data
```

**Review by Yu-jinKim — COMMENTED** [review]
Added python job termination

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/132#-:-O6zqqFZ2FiWnyBKhLVK:b-amzpem)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 547 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/132#-O6zGbflAbupOnsdNGJU:-O6zpQ_56eOURKBQxquC:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/5b94db83c4a1aa0e4b35d3e84c1b2eec735fac84/resources/home/dnanexus/run_workflows/run_workflows.py#L547)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

here the only thing we send a Slack alert for is if the ticket assay field has more than one, so we don't catch if there's:
- no tickets
- too many tickets
- ticket assay doesn't match our assay config

I think it might be better to define an empty list of errors, then append error messages to each for any of the above then check at the end and send Slack alert if any found
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/run_workflows/run_workflows.py` line 829 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/132#-O6zHt7I5znmqc3a-pnZ:-O6zp_7RB3dOE6h3Jdrq:bl5c8mq) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/5b94db83c4a1aa0e4b35d3e84c1b2eec735fac84/resources/home/dnanexus/run_workflows/run_workflows.py#L829)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

what is data? don't you store the ticket ID in `dx_builder.config_to_samples` above?
</blockquote></details>

data is the data stored for the config i.e. samples, dxproject, ticket, config content...
I'm actually thinking of trying to simplify the data structure by creating one dx_builder object per assay used. I think that would ease the understanding of the script by just having attributes for everything instead of relying on a fat dict to get the data. Probably next PR

**Review by jethror1 — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/132)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/132)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
