### PR TITLE
In 711 handle multiple configs - Part 1

### PR DESCRIPTION
**Pull request by Yu-jinKim**
- Starting DXBuilder conversion
- Start adapting `run_workflows`
- Move functions around to `dx_utils`

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/125)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/125)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @Yu-jinKim)

___
*[`resources/home/dnanexus/run_workflows/utils/dx_requests.py` line 805 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/125#-O3I7WF47jmYeXQvsuwM:-O3I7WF47jmYeXQvsuwN:b-q4bqnv) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8aac7836054f9396c74536f6c2ca5b3128d58bbe/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L805)):*
> ```Python
>             self.samples = random.sample(self.samples, limit_nb)
> 
>         d = {}
> ```

longer pls



_Code quote:_
```Python
 d = {}
```
___
*[`resources/home/dnanexus/run_workflows/utils/dx_requests.py` line 830 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/125#-O3I7c657psHgLDBCZHx:-O3I7c657psHgLDBCZHy:b-2epo42) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8aac7836054f9396c74536f6c2ca5b3128d58bbe/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L830)):*
> ```Python
>         """
> 
>         d = {}
> ```

longer plssss



_Code quote:_
```Python
d = {}
```
___
*[`resources/home/dnanexus/run_workflows/utils/dx_requests.py` line 943 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/125#-O3I7r_Y2GrrohLsVNAt:-O3I7r_Y2GrrohLsVNAu:b-ryf7bq) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8aac7836054f9396c74536f6c2ca5b3128d58bbe/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L943)):*
> ```Python
>                 )
> 
>         # TODO handle the bash part to send the slack message
> ```

is this the best way if we're just sticking with Python? or is this moved and to change later?



_Code quote:_
```Python
            # write analysis project to file to pick up at end to send Slack message
            with open(log_file_name, 'w') as fh:
                fh.write(
                    f"{data['project'].describe()['id']} "
                    f"{config.get('assay_code')} "
                    f"{config.get('version')}\n"
                )

        # TODO handle the bash part to send the slack message
```

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/125)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/run_workflows/utils/dx_requests.py` line 943 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/125#-O3I7r_Y2GrrohLsVNAt:-O3IKl6tAxLoxRNViIgI:b-fm6vdl) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8aac7836054f9396c74536f6c2ca5b3128d58bbe/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L943)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this the best way if we're just sticking with Python? or is this moved and to change later?
</blockquote></details>

i guess this can be thought about.
I just saw it was used in the bash and put that down for future yujin

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/125)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`resources/home/dnanexus/run_workflows/utils/dx_requests.py` line 805 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/125#-O3I7WF47jmYeXQvsuwM:-O3ILT5g-n8qNQatq6E-:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8aac7836054f9396c74536f6c2ca5b3128d58bbe/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L805)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

longer pls
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/run_workflows/utils/dx_requests.py` line 830 at r1](https://reviewable.io/reviews/eastgenomics/eggd_conductor/125#-O3I7c657psHgLDBCZHx:-O3ILTQA3qqEoZ7Va2GW:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_conductor/blob/8aac7836054f9396c74536f6c2ca5b3128d58bbe/resources/home/dnanexus/run_workflows/utils/dx_requests.py#L830)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

longer plssss
</blockquote></details>

Done.

**Review by jethror1 — APPROVED** [review]
> Reviewed 3 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/125)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_conductor/125)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Yu-jinKim)

**Pull request merged**
